# Generated by Django 5.0.6 on 2025-02-28 02:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], default='IN', max_length=3)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('F', 'Finalizado'), ('A', 'Anulado')], default='P', max_length=1)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier')),
            ],
            options={
                'verbose_name': 'Movement',
                'verbose_name_plural': 'Movements',
            },
        ),
        migrations.CreateModel(
            name='MovementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inv.movement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
