# Generated by Django 5.0.6 on 2024-12-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('F', 'Finalizado'), ('A', 'Anulado')], default='P', max_length=1),
        ),
    ]
