# Generated by Django 5.1.7 on 2025-04-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_productentry_productentrydetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productentrydetail',
            name='unit_cost',
        ),
        migrations.AlterField(
            model_name='productentrydetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
