# Generated by Django 5.1.7 on 2025-04-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_remove_productentrydetail_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentrydetail',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
