# Generated by Django 5.1.7 on 2025-04-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_productentrydetail_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentrydetail',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
