# Generated by Django 5.1.7 on 2025-04-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_alter_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
