# Generated by Django 5.1.7 on 2025-04-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_alter_productentrydetail_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementdetail',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='movementdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='MovementDetail',
        ),
    ]
