# Generated by Django 5.0.6 on 2025-07-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_purchasedetail_sale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AddField(
            model_name='movementitem',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementitem',
            name='stock_after_movement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movementitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
