# Generated by Django 5.0.6 on 2025-07-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_alter_purchase_options_movementitem_observation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementitem',
            name='subtotal',
        ),
    ]
