# Generated by Django 5.0.6 on 2026-05-06 03:17

from django.db import migrations
from django.db.models import F


def fill_unit_price(apps, schema_editor):
    """Rellena unit_price NULL con el costo actual del producto"""
    MovementItem = apps.get_model('inv', 'MovementItem')
    
    # Obtener todos los MovementItem con unit_price NULL
    items_without_price = MovementItem.objects.filter(unit_price__isnull=True)
    
    for item in items_without_price:
        # Usar el costo actual del producto como aproximación histórica
        item.unit_price = item.product.cost or 0
        item.save()


def reverse_fill_unit_price(apps, schema_editor):
    """Reversa: establecer unit_price NULL nuevamente"""
    MovementItem = apps.get_model('inv', 'MovementItem')
    MovementItem.objects.all().update(unit_price=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_remove_movementitem_subtotal'),
    ]

    operations = [
        migrations.RunPython(fill_unit_price, reverse_fill_unit_price),
    ]
