# Generated by Django 5.1.7 on 2025-04-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_alter_purchase_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['status', 'date'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
