# Generated by Django 5.0.6 on 2026-08-09 04:19

import django.db.models.deletion
from django.db import migrations, models


def assign_legacy_warehouse(apps, schema_editor):
    Warehouse = apps.get_model('core', 'Warehouse')
    Purchase = apps.get_model('inv', 'Purchase')
    Movement = apps.get_model('inv', 'Movement')

    warehouse = Warehouse.objects.filter(code='LEGACY').first()
    if warehouse is None:
        return

    Purchase.objects.filter(warehouse__isnull=True).update(warehouse=warehouse)
    Movement.objects.filter(warehouse__isnull=True).update(warehouse=warehouse)


def unassign_legacy_warehouse(apps, schema_editor):
    Warehouse = apps.get_model('core', 'Warehouse')
    Purchase = apps.get_model('inv', 'Purchase')
    Movement = apps.get_model('inv', 'Movement')

    warehouse = Warehouse.objects.filter(code='LEGACY').first()
    if warehouse is None:
        return

    Purchase.objects.filter(warehouse=warehouse).update(warehouse=None)
    Movement.objects.filter(warehouse=warehouse).update(warehouse=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_simplify_global_warehouses'),
        ('inv', '0008_fill_movement_item_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.warehouse'),
        ),
        migrations.RunPython(assign_legacy_warehouse, unassign_legacy_warehouse),
    ]
