# Generated by Django 5.0.6 on 2024-12-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTADO', 'Ejecutado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10),
        ),
    ]
