# Generated by Django 5.0.6 on 2025-03-08 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to=settings.AUTH_USER_MODEL),
        ),
    ]
