# Generated by Django 5.0.6 on 2025-03-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proforma_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='latest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
