# Generated by Django 5.1.7 on 2025-03-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_proforma_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='observation',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
