# Generated by Django 5.1.7 on 2025-03-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_proforma_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proforma',
            name='observation',
        ),
        migrations.AddField(
            model_name='proforma',
            name='observacion',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre la proforma', max_length=200, null=True),
        ),
    ]
