# Generated by Django 5.0.6 on 2025-08-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('BOB', 'Boliviano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
    ]
