# Generated by Django 5.0.6 on 2025-11-12 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_username_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to='core.company'),
        ),
    ]
