# Generated by Django 5.0.6 on 2025-12-30 04:22

from django.db import migrations
from django.utils import timezone

def create_initial_price_history(apps, schema_editor):
    Producto = apps.get_model('core', 'Producto')
    PriceHistory = apps.get_model('core', 'ProductPriceHistory')
    User = apps.get_model('core', 'User')

    # Evitar asumir IDs fijos en instalaciones nuevas.
    system_user = User.objects.order_by('id').first()
    if not system_user:
        # Sin usuarios no se puede poblar created_by/approved_by; salimos sin error.
        return

    for producto in Producto.objects.all():
        PriceHistory.objects.create(
            product=producto,
            old_price=None,
            new_price=producto.precio,
            cost_reference=producto.cost,
            change_type='INITIAL',
            reason='Initial price migration',
            status='APPROVED',
            valid_from=timezone.now(),
            created_by=system_user,
            approved_by=system_user,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productpricehistory'),
    ]

    operations = [
        migrations.RunPython(create_initial_price_history),
    ]
