# Generated by Django 5.0.6 on 2026-03-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_initial_price_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_product_kits',
            field=models.BooleanField(default=True, help_text='Permite usar kits de productos en las proformas', verbose_name='Habilitar Kits de Productos'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=10),
        ),
    ]
