# Generated by Django 5.0.6 on 2026-03-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_company_enable_product_kits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='product_custom_fields_config',
            field=models.JSONField(blank=True, default=dict, help_text='Define campos adicionales para productos. Ejemplo: {"color": {"type": "text", "label": "Color", "required": false}}', verbose_name='Configuración de Campos Personalizados'),
        ),
        migrations.AddField(
            model_name='producto',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Almacena valores de campos personalizados definidos por la empresa', verbose_name='Atributos Personalizados'),
        ),
    ]
