# Generated by Django 5.0.6 on 2026-03-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_username_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_product_recommendations',
            field=models.BooleanField(default=True, help_text='Muestra sugerencias de productos en proformas según historial de proformas ejecutadas', verbose_name='Habilitar Productos Recomendados'),
        ),
    ]