# Generated by Django 5.0.6 on 2026-04-14 15:14

from django.db import migrations, models


def assign_roles(apps, schema_editor):
    User = apps.get_model('core', 'User')

    for user in User.objects.all():
        if getattr(user, 'is_superuser', False):
            user.role = 'SUPERADMIN'
        elif user.groups.filter(name='Administrador').exists():
            user.role = 'ADMIN'
        elif user.groups.filter(name='Almacen').exists() or user.groups.filter(name='Contabilidad').exists():
            user.role = 'ALMACEN'
        elif user.groups.filter(name='Ventas').exists():
            user.role = 'VENTAS'
        else:
            user.role = 'VENTAS'

        user.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_company_enable_product_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('VENTAS', 'Ventas'), ('ALMACEN', 'Almacén'), ('CAJA', 'Caja')], default='VENTAS', max_length=20, verbose_name='Rol'),
        ),
        migrations.RunPython(assign_roles, migrations.RunPython.noop),
    ]
