# Generated by Django 5.2.4 on 2026-04-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('BOB', 'Boliviano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], max_length=3, verbose_name='Moneda origen')),
                ('to_currency', models.CharField(choices=[('BOB', 'Boliviano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], max_length=3, verbose_name='Moneda destino')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Tipo de cambio')),
                ('valid_from', models.DateField(verbose_name='Vigente desde')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exchange_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'ordering': ['-valid_from', '-created_at'],
                'unique_together': {('company', 'from_currency', 'to_currency', 'valid_from')},
            },
        ),
        migrations.AddField(
            model_name='proforma',
            name='currency_source',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Moneda origen'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='currency_target',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Moneda destino'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='exchange_rate_applied',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Tipo de cambio aplicado'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='exchange_rate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del tipo de cambio'),
        ),
    ]
