# Generated by Django 5.0.6 on 2026-04-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_exchangerate_and_proforma_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='referencia_cruzada',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
