# Generated by Django 5.0.6 on 2026-04-23 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_producto_referencia_cruzada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to=settings.AUTH_USER_MODEL),
        ),
    ]
