# Generated by Django 5.0.6 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_initial_stock_load',
            field=models.BooleanField(
                default=True,
                help_text='Permite acceder al módulo de carga inicial de stock',
                verbose_name='Habilitar Carga Inicial de Stock',
            ),
        ),
    ]
