# Generated by Django 5.0.6 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_company_enable_initial_stock_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_cloud_catalog',
            field=models.BooleanField(
                default=True,
                help_text='Permite acceder a la importación desde catálogo nube en productos',
                verbose_name='Habilitar Catálogo Nube',
            ),
        ),
    ]
