# Generated by Django 5.0.6 on 2026-07-19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_company_enable_cloud_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_sale_margin_percentage',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('35'),
                help_text='Porcentaje usado para sugerir precio de venta desde costo en compras (ej: 35.00)',
                max_digits=5,
                verbose_name='Margen de Venta por Defecto (%)',
            ),
        ),
    ]
