# Generated by Django 5.0.6 on 2026-08-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_initialize_legacy_warehouse_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='unique_warehouse_code_per_company',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='company',
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_warehouse_code'),
        ),
    ]
