# Generated by Django 5.0.6 on 2026-08-09 04:25

import django.db.models.deletion
from django.db import migrations, models


def assign_legacy_warehouse(apps, schema_editor):
    Warehouse = apps.get_model('core', 'Warehouse')
    Proforma = apps.get_model('core', 'Proforma')
    warehouse = Warehouse.objects.filter(code='LEGACY').first()
    if warehouse is not None:
        Proforma.objects.filter(warehouse__isnull=True).update(warehouse=warehouse)


def unassign_legacy_warehouse(apps, schema_editor):
    Warehouse = apps.get_model('core', 'Warehouse')
    Proforma = apps.get_model('core', 'Proforma')
    warehouse = Warehouse.objects.filter(code='LEGACY').first()
    if warehouse is not None:
        Proforma.objects.filter(warehouse=warehouse).update(warehouse=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_simplify_global_warehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='core.warehouse'),
        ),
        migrations.RunPython(assign_legacy_warehouse, unassign_legacy_warehouse),
    ]
