# Generated by Django 5.0.6 on 2026-08-09 05:28

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_users_to_default_warehouse(apps, schema_editor):
    Warehouse = apps.get_model('core', 'Warehouse')
    User = apps.get_model('core', 'User')
    warehouse = Warehouse.objects.filter(is_active=True, is_default=True).first()
    if warehouse is not None:
        User.objects.filter(default_warehouse__isnull=True).update(default_warehouse=warehouse)


def unassign_existing_users(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.update(default_warehouse=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_warehouse_to_proformas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='core.warehouse', verbose_name='Almacén predeterminado'),
        ),
        migrations.RunPython(assign_existing_users_to_default_warehouse, unassign_existing_users),
    ]
